# Generated by Django 5.2 on 2025-10-02 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_apartment_order_city_order_country_order_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
