# Generated by Django 5.2 on 2025-09-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_product_cartitem_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='category',
            new_name='product_category',
        ),
    ]
