# Generated by Django 5.2 on 2025-09-13 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcategory_currencycode_productcategory_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
