# Generated by Django 5.2 on 2025-10-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_stock_productcategory_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='same_category_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='weight_grams',
            field=models.BooleanField(default=False),
        ),
    ]
