# Generated by Django 5.2 on 2025-10-09 22:04

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productlandingimage_productlandingvideo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlandingvideo',
            name='video',
        ),
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to=products.models.upload_product_video_landing_page)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_video', to='products.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='productlandingvideo',
            name='video_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_video_landing', to='products.productvideo'),
        ),
    ]
