# Generated by Django 5.2 on 2025-10-09 22:56

import django.db.models.deletion
import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productlandingvideo_video_productvideo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageLand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.FileField(upload_to=products.models.upload_product_image_landing_page)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=products.models.upload_testimonial_landing_page)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('product_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='productlandingimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producttestimonials',
            name='description',
        ),
        migrations.RemoveField(
            model_name='producttestimonials',
            name='image',
        ),
        migrations.RemoveField(
            model_name='producttestimonials',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productvideo',
            name='product_category',
        ),
        migrations.AddField(
            model_name='productvideo',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productlandingimage',
            name='image_category_land',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_image_landing', to='products.productimageland'),
        ),
        migrations.AddField(
            model_name='producttestimonials',
            name='testimonial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonial_category', to='products.testimonialdetail'),
        ),
    ]
