# Generated by Django 5.2 on 2025-10-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productimageland_testimonialdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlandingimage',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productlandingimage',
            name='title',
        ),
        migrations.AddField(
            model_name='productimageland',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimageland',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
