# Generated by Django 5.2 on 2025-10-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_productlandingimage_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='shipping_time_asia',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='shipping_time_europe',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='shipping_time_usa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='shipping_time_woldwide',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
