# Generated by Django 5.2 on 2025-10-13 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_productcategory_shipping_time_asia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='weight_grams',
        ),
    ]
