# Generated by Django 5.2 on 2025-10-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_remove_productcategory_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='color',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='size',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='weight_grams',
            field=models.BooleanField(default=False),
        ),
    ]
