# Generated by Django 5.2 on 2025-10-13 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productcategory_color_productcategory_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='size',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='weight_grams',
        ),
        migrations.AddField(
            model_name='productcategory',
            name='colors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='sizes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='weight_gram',
            field=models.BooleanField(default=False),
        ),
    ]
